In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [8]:
x.numel()

12

In [10]:
x.reshape(4, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [12]:
torch.zeros((3, 4, 2))

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [13]:
torch.ones((3,4,2))

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [54]:
torch.tensor([2.,3,4])

tensor([2., 3., 4.])

In [55]:
a = torch.tensor([1.,2,3,4])

In [56]:
b = torch.tensor([2,2,2,2])

In [57]:
a+b, a-b, a*b, a/b, a**b

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]))

In [20]:
torch.exp(a)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))

In [58]:
Y = torch.tensor([[3.,1,2,4],[1,2,3,4],[4,2,3,1]])

In [59]:
X, Y

(tensor([[ 0.,  1., 19.,  3.],
         [ 4.,  5., 19.,  7.],
         [ 8.,  9., 19.,  3.]]),
 tensor([[3., 1., 2., 4.],
         [1., 2., 3., 4.],
         [4., 2., 3., 1.]]))

In [24]:
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 3.,  1.,  2.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  2.,  3.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  3.,  1.,  2.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  2.,  3.,  1.]]))

In [26]:
X == Y

tensor([[False,  True,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()

tensor(66.)

In [28]:
# 广播
a = torch.arange(3).reshape(1,3)

In [29]:
a

tensor([[0, 1, 2]])

In [30]:
b = torch.arange(2).reshape(2,1)

In [31]:
b

tensor([[0],
        [1]])

In [32]:
a + b

tensor([[0, 1, 2],
        [1, 2, 3]])

In [33]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X[2, 3] = 3

In [39]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  3.]])

In [40]:
X[:,2] = 19

In [41]:
X

tensor([[ 0.,  1., 19.,  3.],
        [ 4.,  5., 19.,  7.],
        [ 8.,  9., 19.,  3.]])

In [42]:
# 减少内存损耗
# 多使用 X += Y  or  X[:] = X + Y

In [43]:
type(X.numpy())

numpy.ndarray

In [60]:
a = torch.tensor([1.1])

In [61]:
a, a.item(), float(a), int(a)

(tensor([1.1000]), 1.100000023841858, 1.100000023841858, 1)